development:
  host: localhost
  database: vlctechhub_development

test:
  host: localhost
  database: vlctechhub_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
